<?php

namespace ContainerBWqWAiP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Il_WMUeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Il.wMUe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Il.wMUe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'jobCategoryRepository' => ['privates', 'App\\Repository\\JobCategoryRepository', 'getJobCategoryRepositoryService', true],
            'jobOfferRepository' => ['privates', 'App\\Repository\\JobOfferRepository', 'getJobOfferRepositoryService', true],
        ], [
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'entityManager' => '?',
            'jobCategoryRepository' => 'App\\Repository\\JobCategoryRepository',
            'jobOfferRepository' => 'App\\Repository\\JobOfferRepository',
        ]);
    }
}
