<?php

namespace ContainerBWqWAiP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobOfferService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7f85tW6.App\Entity\JobOffer' shared service.
     *
     * @return \App\Entity\JobOffer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7f85tW6": it needs an instance of "App\\Entity\\JobOffer" but this type has been excluded in "config/services.yaml".');
    }
}
