<?php

namespace ContainerJJx3tXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9IwIY8nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9IwIY8n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9IwIY8n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adminRepository' => ['privates', 'App\\Repository\\AdminRepository', 'getAdminRepositoryService', true],
            'candidateRepository' => ['privates', 'App\\Repository\\CandidateRepository', 'getCandidateRepositoryService', true],
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'jobOfferRepository' => ['privates', 'App\\Repository\\JobOfferRepository', 'getJobOfferRepositoryService', true],
        ], [
            'adminRepository' => 'App\\Repository\\AdminRepository',
            'candidateRepository' => 'App\\Repository\\CandidateRepository',
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'jobOfferRepository' => 'App\\Repository\\JobOfferRepository',
        ]);
    }
}
