<?php

namespace ContainerJJx3tXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MRhoQQbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MRhoQQb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MRhoQQb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'candidateRepository' => ['privates', 'App\\Repository\\CandidateRepository', 'getCandidateRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.MRhoQQb.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.MRhoQQb": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'candidateRepository' => 'App\\Repository\\CandidateRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
