<?php

namespace ContainerJJx3tXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7f85tW6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7f85tW6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7f85tW6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jobOffer' => ['privates', '.errored..service_locator.7f85tW6.App\\Entity\\JobOffer', NULL, 'Cannot autowire service ".service_locator.7f85tW6": it needs an instance of "App\\Entity\\JobOffer" but this type has been excluded in "config/services.yaml".'],
        ], [
            'jobOffer' => 'App\\Entity\\JobOffer',
        ]);
    }
}
