<?php

namespace ContainerJJx3tXc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MpvB1I8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MpvB1I8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MpvB1I8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'candidateRepository' => ['privates', 'App\\Repository\\CandidateRepository', 'getCandidateRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'jobCategoryRepository' => ['privates', 'App\\Repository\\JobCategoryRepository', 'getJobCategoryRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.MpvB1I8.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.MpvB1I8": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'candidateRepository' => 'App\\Repository\\CandidateRepository',
            'entityManager' => '?',
            'jobCategoryRepository' => 'App\\Repository\\JobCategoryRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
