<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Candidate extends \App\Entity\Candidate implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'applications' => [parent::class, 'applications', null],
        "\0".parent::class."\0".'availability' => [parent::class, 'availability', null],
        "\0".parent::class."\0".'birth_location' => [parent::class, 'birth_location', null],
        "\0".parent::class."\0".'birthdate' => [parent::class, 'birthdate', null],
        "\0".parent::class."\0".'completeProfile' => [parent::class, 'completeProfile', null],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'current_location' => [parent::class, 'current_location', null],
        "\0".parent::class."\0".'cv' => [parent::class, 'cv', null],
        "\0".parent::class."\0".'deleted' => [parent::class, 'deleted', null],
        "\0".parent::class."\0".'deleted_at' => [parent::class, 'deleted_at', null],
        "\0".parent::class."\0".'experience' => [parent::class, 'experience', null],
        "\0".parent::class."\0".'files' => [parent::class, 'files', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'job_category_id' => [parent::class, 'job_category_id', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'nationality' => [parent::class, 'nationality', null],
        "\0".parent::class."\0".'passport' => [parent::class, 'passport', null],
        "\0".parent::class."\0".'passport_file' => [parent::class, 'passport_file', null],
        "\0".parent::class."\0".'profile_picture' => [parent::class, 'profile_picture', null],
        "\0".parent::class."\0".'short_description' => [parent::class, 'short_description', null],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'address' => [parent::class, 'address', null],
        'applications' => [parent::class, 'applications', null],
        'availability' => [parent::class, 'availability', null],
        'birth_location' => [parent::class, 'birth_location', null],
        'birthdate' => [parent::class, 'birthdate', null],
        'completeProfile' => [parent::class, 'completeProfile', null],
        'country' => [parent::class, 'country', null],
        'created_at' => [parent::class, 'created_at', null],
        'current_location' => [parent::class, 'current_location', null],
        'cv' => [parent::class, 'cv', null],
        'deleted' => [parent::class, 'deleted', null],
        'deleted_at' => [parent::class, 'deleted_at', null],
        'experience' => [parent::class, 'experience', null],
        'files' => [parent::class, 'files', null],
        'firstname' => [parent::class, 'firstname', null],
        'gender' => [parent::class, 'gender', null],
        'id' => [parent::class, 'id', null],
        'job_category_id' => [parent::class, 'job_category_id', null],
        'lastname' => [parent::class, 'lastname', null],
        'nationality' => [parent::class, 'nationality', null],
        'passport' => [parent::class, 'passport', null],
        'passport_file' => [parent::class, 'passport_file', null],
        'profile_picture' => [parent::class, 'profile_picture', null],
        'short_description' => [parent::class, 'short_description', null],
        'updated_at' => [parent::class, 'updated_at', null],
        'user' => [parent::class, 'user', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
