<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JobOffer extends \App\Entity\JobOffer implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activity' => [parent::class, 'activity', null],
        "\0".parent::class."\0".'applications' => [parent::class, 'applications', null],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null],
        "\0".parent::class."\0".'closing_date' => [parent::class, 'closing_date', null],
        "\0".parent::class."\0".'creation_date' => [parent::class, 'creation_date', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'job_category' => [parent::class, 'job_category', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null],
        "\0".parent::class."\0".'salary' => [parent::class, 'salary', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'activity' => [parent::class, 'activity', null],
        'applications' => [parent::class, 'applications', null],
        'client' => [parent::class, 'client', null],
        'closing_date' => [parent::class, 'closing_date', null],
        'creation_date' => [parent::class, 'creation_date', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'job_category' => [parent::class, 'job_category', null],
        'location' => [parent::class, 'location', null],
        'notes' => [parent::class, 'notes', null],
        'salary' => [parent::class, 'salary', null],
        'title' => [parent::class, 'title', null],
        'type' => [parent::class, 'type', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
