<?php

namespace ContainerTD4txti;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MqVvURBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MqVvURB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MqVvURB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jobOffer' => ['privates', '.errored..service_locator.MqVvURB.App\\Entity\\JobOffer', NULL, 'Cannot autowire service ".service_locator.MqVvURB": it needs an instance of "App\\Entity\\JobOffer" but this type has been excluded in "config/services.yaml".'],
            'jobOfferRepository' => ['privates', 'App\\Repository\\JobOfferRepository', 'getJobOfferRepositoryService', true],
        ], [
            'jobOffer' => 'App\\Entity\\JobOffer',
            'jobOfferRepository' => 'App\\Repository\\JobOfferRepository',
        ]);
    }
}
