controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_candidate_new:
    path: /candidates/new/{id}
    controller: App\Controller\CandidateController::new