<?php

namespace ContainerPNeWMwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AqZlwNKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AqZlwNK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AqZlwNK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'application' => ['privates', '.errored.Zidp1X.', NULL, 'Cannot determine controller argument for "App\\Controller\\AdminController::job_application_delete()": the $application argument is type-hinted with the non-existent class or interface: "App\\Controller\\Application". Did you forget to add a use statement?'],
            'applicationRepository' => ['privates', 'App\\Repository\\ApplicationRepository', 'getApplicationRepositoryService', true],
        ], [
            'application' => '?',
            'applicationRepository' => 'App\\Repository\\ApplicationRepository',
        ]);
    }
}
