<?php

namespace ContainerPNeWMwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ua18XYoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ua18XYo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ua18XYo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'candidate' => ['privates', '.errored..service_locator.Ua18XYo.App\\Entity\\Candidate', NULL, 'Cannot autowire service ".service_locator.Ua18XYo": it needs an instance of "App\\Entity\\Candidate" but this type has been excluded in "config/services.yaml".'],
            'candidateRepository' => ['privates', 'App\\Repository\\CandidateRepository', 'getCandidateRepositoryService', true],
        ], [
            'candidate' => 'App\\Entity\\Candidate',
            'candidateRepository' => 'App\\Repository\\CandidateRepository',
        ]);
    }
}
