<?php

namespace ContainerPNeWMwn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G4kCoBeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G4kCoBe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G4kCoBe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'applicationRepository' => ['privates', 'App\\Repository\\ApplicationRepository', 'getApplicationRepositoryService', true],
        ], [
            'applicationRepository' => 'App\\Repository\\ApplicationRepository',
        ]);
    }
}
