<?php

namespace ContainerJN64tKX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CHhMnL8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cHhMnL8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cHhMnL8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'application' => ['privates', '.errored..service_locator.cHhMnL8.App\\Entity\\Application', NULL, 'Cannot autowire service ".service_locator.cHhMnL8": it needs an instance of "App\\Entity\\Application" but this type has been excluded in "config/services.yaml".'],
            'applicationRepository' => ['privates', 'App\\Repository\\ApplicationRepository', 'getApplicationRepositoryService', true],
        ], [
            'application' => 'App\\Entity\\Application',
            'applicationRepository' => 'App\\Repository\\ApplicationRepository',
        ]);
    }
}
