<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFntbgaa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFntbgaa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFntbgaa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFntbgaa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFntbgaa\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fntbgaa',
    'container.build_id' => '5237e208',
    'container.build_time' => 1682421730,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFntbgaa');
